name: Create and publish a Docker image to GitHub Container Registry

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
      file_path:
        required: true
        type: string
      context_path:
        required: true
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

env:
  REGISTRY: ghcr.io

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context_path }}
          file: ${{ inputs.file_path }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ inputs.image_name }}:${{ inputs.tag }}

      - name: Notify to Slack
        uses: 8398a7/action-slack@v3.8.0
        with:
          status: ${{ job.status }}
          author_name: ${{ inputs.image_name }}
          fields: repo,message,commit,author,action,job,took,eventName,ref,workflow # TODO: Remove unused
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.GHCR_NOTIFY_SLACK_WEBHOOK_URL }}
        if: always()
